
###artist dashboard
GET http://localhost:3000/api/dashboard/artist/67a75d5f7c0154c68fa43050

###manager dashboard
GET http://localhost:3000/api/dashboard/manager/67a3be671f2927a6985e5461


###admin dashboard
GET http://localhost:3000/api/dashboard/admin

